### PR TITLE
Fix Solarized Dark Theme

### PR DESCRIPTION
**Pull request by amanrajOO7**

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
Why though?

**Comment by NurKeinNeid** [comment]
Besides, you call it "fix." What's fixed? You actually change the color value for this primary.

**Comment by amanrajOO7** [comment]
The hex is the fix only. The earlier hex value for dark settings is too dark & it doesn't match.

**Comment by NurKeinNeid** [comment]
Yes, I understand and will get merged for sure. I just don't like generic commit messages like that. Once you start like that, everything is called "fix" in the end. How will you know what's been done and distinguish? It should describe what you changed or what you had in mind.

**Comment by idoybh** [comment]
> Yes, I understand and will get merged for sure. I just don't like generic commit messages like that. Once you start like that, everything is called "fix" in the end. How will you know what's been done and distinguish? It should describe what you changed or what you had in mind.

That's because I told him I will amend this to the original commit

**Comment by idoybh** [comment]
I was late doing that. Sorry both of ya

**Review by idoybh — APPROVED** [review]

**Pull request merged**
